### PR TITLE
New layout for fossasia10

### PR DESCRIPTION
**Pull request by wongalvis**
Whole new layout for fossasia10, improved experience for mobile users.
Preview at here: http://pwmvx1289.github.io/fossasia10/

### CODE REVIEW

**Comment by wongalvis** [comment]
@RoonyH @mariobehling What do you think about it?

**Comment by mariobehling** [comment]
Hi, this merge conflicted with another merge. Could you help us and update the current files, please? It would be awesome. Thank you.

**Comment by wongalvis** [comment]
@mariobehling I was recommended by @RoonyH to work on it. I don't know about the situation of @samarjeet27

**Comment by samarsault** [comment]
@pwmvx1289 @mariobehling recommended me to

**Comment by mariobehling** [comment]
I think a lot of your changes are complimentary. We can merge the work of both of you and make a new task for you if there is not task left. Please check how you can merge your improvements with the previous commit. Good work. Thank you!

**Comment by wongalvis** [comment]
@mariobehling I think my new layout solves all the issue mentioned by @samarjeet27 , along with some additional improvements. It is quite a big revamp. Have you take a look at it?

**Comment by samarjeet27** [comment]
@mariobehling , I can try merging please add the fossasia10 repo to the list.

**Comment by mariobehling** [comment]
Hi, your site idea looks very nice. It would be great, if we could work together on this more. Are you interested?

**Comment by wongalvis** [comment]
@mariobehling Yes of course it's my pleasure :)

**Pull request closed without merging**
