### PR TITLE
New layout for fossasia10

### PR DESCRIPTION
**Pull request by wongalvis**
Whole new layout for fossasia10, additional improvements, enhanced experience for mobile users. manually rebased from the work done by @samarjeet27 
Preview at here: http://pwmvx1289.github.io/fossasia10/
Original pull request here: https://github.com/fossasia/fossasia10/pull/26

### CODE REVIEW

**Comment by wongalvis** [comment]
@RoonyH @eMBee What do you think about it?

**Comment by wongalvis** [comment]
@mariobehling What's your idea about taking it further?

**Comment by mariobehling** [comment]
Hi, I merged it. It looks great and the space is used much better. However, would be great to work on  some design questions, e.g. the photos are not using 100% of the available width. There is no sidebar anymore. I can see, why this would be good, but this means that new content of twitter and the subscribe button is now moved down. New content should be usually immediately available to site visitors. What do you think? Interested to work on implementing a sidebar? I can make a task for you, if you want.

**Comment by wongalvis** [comment]
@mariobehling Images are scaled down in large screen sizes since a number of them do not have resolutions high enough. The sidebar is removed since the height of the main content varies a lot and it makes the interface odd if there's two columns (Main content and side bar). A message box telling users to subscribe could be added.

**Comment by mariobehling** [comment]
Ok, so I know that the images have different sizes. We can rescale them. The question is, how can we have the sidebar content back again? Can we change the style to increase the width. What do you propose?

**Comment by wongalvis** [comment]
@mariobehling The issue concerned about having a sidebar is that the height of the main content area  varies a lot across different pages, in some pages it is too short compared to the sidebar, and in the others too long. So the sidebar is removed to resolve the issue.

**Comment by mariobehling** [comment]
This issue was solved in the 2011 site as well. Just make sure, that the areas do not overlap. http://fossasia.github.io/fossasia11/

**Comment by wongalvis** [comment]
@mariobehling Sidebar implemented in https://github.com/fossasia/fossasia10/pull/29

**Comment by mariobehling** [comment]
What's the link? Where is the task?

**Comment by pwmvx1289** [comment]
It's the task currently claimed by @samarjeet27 , it would be great if he could post the link here.

**Comment by mariobehling** [comment]
Several people can work on this as it involved several sub tasks. We can have a number of tasks here. You can claim this one for example: https://www.google-melange.com/gci/task/view/google/gci2014/5819429313052672

Then just solve some issues on the tracker here.

**Comment by wongalvis** [comment]
I see nice thanks. :D
I'll work on the issues and keep the site improving.

**Comment by mariobehling** [comment]
here is one more: https://www.google-melange.com/gci/task/view/google/gci2014/5845197170671616

**Pull request merged**
